close all;
clear all;
format long;
rp=input('Enter the passband ripple :');
rs=input('Enter the stopband ripple :');
wp=input('Enter the passband frequency :');
ws=input('Enter the stopband frequency :');
fs=input('Sampling freequency : ');
w1=2*wp/fs;
w2=2*ws/fs;
[n,wn]=buttord(w1,w2,rp,rs);
[b,a]=butter(n,[w1,w2],'stop');
w=0:0.1:pi;
[h,om]=freqz(b,a,w);
an=angle(h);
m=20*log(abs(h));
subplot(1,2,1);
plot(om/pi,an);
title(' phase plot ');
xlabel(' frequency ');
ylabel(' phase ');
grid;
subplot(1,2,2);
plot(om/pi,m);
title('magnitude plot');
xlabel(' frequency ');
ylabel(' magnitude ');
grid;
