clear all;
clc;
rp=input('Passband attenuatoin :');
rs=input('Stopband attenuatoin :');
wp=input('Passband Frequency :');
ws=input('Stopband Frequency :');
fs=input('Sampling frequency :');
w1=2*wp/fs;
w2=2*ws/fs;
[n,wn]=cheb1ord(w1,w2,rp,rs);
[b,a]=cheby1(n,rp,wn,'low');
w=0:0.01:pi;
[h,om]=freqz(b,a,w);
an=angle(h);
m=20*log(abs(h));
subplot(2,2,1);
plot(om/pi,m);
axis([0 1 -6 0]);
subplot(2,2,2);
plot(om/pi,an);
% chebyshev 2
[n,wn]=cheb2ord(w1,w2,rp,rs);
[b,a]=cheby2(n,rp,wn,'low');
w=0:0.01:pi;
[h,om]=freqz(b,a,w);
an=angle(h);
m=20*log(abs(h));
subplot(2,2,3);
plot(om/pi,m);
axis([0 1 -.2 0]);
subplot(2,2,4);
plot(om/pi,an);